// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7jkVKcfGGjQko_f8uN7Ib1vo4qXMGQSs',
    appId: '1:246456467530:web:19f0b8937ff6c3425366b3',
    messagingSenderId: '246456467530',
    projectId: 'surgerey-tracker',
    authDomain: 'surgerey-tracker.firebaseapp.com',
    storageBucket: 'surgerey-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDpLBOni5TsHXpR6uD9wqn-o71YJrkSF8',
    appId: '1:246456467530:android:9770dc41e00bd7085366b3',
    messagingSenderId: '246456467530',
    projectId: 'surgerey-tracker',
    storageBucket: 'surgerey-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr9YfCOEYjk94_rPfmnofPOMES7II-5QM',
    appId: '1:246456467530:ios:6b1e15e3373b090b5366b3',
    messagingSenderId: '246456467530',
    projectId: 'surgerey-tracker',
    storageBucket: 'surgerey-tracker.appspot.com',
    iosClientId: '246456467530-fulf9k4in83n819ngonheq6uh1kgehi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.surgeryTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr9YfCOEYjk94_rPfmnofPOMES7II-5QM',
    appId: '1:246456467530:ios:8cb0b06caabefad15366b3',
    messagingSenderId: '246456467530',
    projectId: 'surgerey-tracker',
    storageBucket: 'surgerey-tracker.appspot.com',
    iosClientId: '246456467530-qgla12rpk2hit8eln1cot5iobupoul6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.surgeryTracker.RunnerTests',
  );
}
